In [2]:
import os
import cv2
import numpy as np
from tqdm import tqdm

REBULID_DATA = False

In [3]:
class DogsVSCats():
    imgsize = 48
    CATS = "PetImages/Cat"
    DOGS = "PetImages/Dog"   #directory names for data
    
    LABELS = {CATS: 0, DOGS: 1}  #labels for the data
    
    training_data = []
    catcount = 0
    dogcount = 0
    
    def make_training_data(self):
        for label in self.LABELS:
            print(label)
            for f in tqdm(os.listdir(label)): #f is a file name in the label(directory)
                try: #weird data 가 들어올 수 있음
                    path = os.path.join(label, f)
                    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
                    img = cv2.resize(img, (self.imgsize, self.imgsize))
                    self.training_data.append([np.array(img), np.eye(2)[self.LABELS[label]]])

                    if label == self.CATS:
                        self.catcount += 1
                    elif label == self.DOGS:
                        self.dogcount += 1
                except Exception as e:
                    pass
                        #print(str(excetion))
        np.random.shuffle(self.training_data)
        np.save("training_date.npy", self.training_data)
        print("Cats:", self.catcount)
        print("Dogs:", self.dogcount)
if REBULID_DATA:
    dogsvcats = DogsVSCats()
    dogsvcats.make_training_data()

  0%|                                                                              | 18/12501 [00:00<01:09, 178.68it/s]

PetImages/Cat


  0%|▏                                                                             | 29/12501 [00:00<00:43, 287.90it/s]

PetImages/Dog


100%|███████████████████████████████████████████████████████████████████████████| 12501/12501 [00:43<00:00, 287.42it/s]


Cats: 12476
Dogs: 12470


In [4]:
training_data = np.load("training_date.npy", allow_pickle=True)

In [5]:
print(len(training_data))

24946


In [6]:
print(training_data[1])

[array([[109, 107, 106, ..., 104,  96,  97],
       [108, 106, 108, ..., 104, 101,  97],
       [110, 108, 110, ..., 102, 100, 100],
       ...,
       [124, 128, 130, ..., 119, 112, 113],
       [126, 125, 130, ..., 111, 108, 113],
       [121, 131, 128, ..., 107, 111, 111]], dtype=uint8)
 array([0., 1.])]


In [7]:
import matplotlib.pyplot as plt

plt.imshow(training_data[1][0], cmap="gray")
plt.show()

<Figure size 640x480 with 1 Axes>

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            #24, 24, 32
            
            nn.Conv2d(32, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            #12, 12, 32
            
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            #6, 6, 64
            
            nn.Conv2d(64, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            #3, 3, 64
        )
        self.fcc = nn.Sequential(
            nn.Linear(576, 32),
            nn.ReLU(),
            nn.Linear(32, 2)
        )
    def forward(self, x):
        x = self.cnn(x)
        x = x.view(x.size(0), -1)
        x = self.fcc(x)
        x = F.softmax(x, dim=1)
        return x

net = Net()

In [9]:
import torch.optim as optim
optimizer = optim.Adam(net.parameters(), lr=1e-3)
loss_function  = nn.MSELoss()

X = torch.Tensor([i[0] for i in training_data]).view(-1, 48, 48)
X = X/255.0
y = torch.Tensor([i[1] for i in training_data])

VAL_PCT = 0.1
val_size = int(len(X)*VAL_PCT)


In [10]:
train_x = X[:-val_size]
train_y = y[:-val_size]

test_x = X[-val_size:]
test_y = y[-val_size:]

print(len(train_x))
print(len(test_x))

22452
2494


In [11]:
batch_size = 100
EPOCHS = 1

for epochs in range(EPOCHS):
    for i in tqdm(range(0, len(train_x), batch_size)):
        batch_x = train_x[i:i+batch_size].view(-1, 1,48,48)
        batch_y = train_y[i:i+batch_size]
        
        net.zero_grad()
        outputs = net(batch_x)
        loss = loss_function(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        if i%10 == 0:
            print(i, " th batch loss : ", loss)
        
        
        

  0%|▎                                                                                 | 1/225 [00:00<02:11,  1.70it/s]

0  th batch loss :  tensor(0.2412, grad_fn=<MseLossBackward>)


  1%|▋                                                                                 | 2/225 [00:01<02:07,  1.75it/s]

100  th batch loss :  tensor(0.2541, grad_fn=<MseLossBackward>)


  1%|█                                                                                 | 3/225 [00:01<01:59,  1.86it/s]

200  th batch loss :  tensor(0.2518, grad_fn=<MseLossBackward>)


  2%|█▍                                                                                | 4/225 [00:02<02:06,  1.75it/s]

300  th batch loss :  tensor(0.2505, grad_fn=<MseLossBackward>)


  2%|█▊                                                                                | 5/225 [00:02<02:07,  1.73it/s]

400  th batch loss :  tensor(0.2570, grad_fn=<MseLossBackward>)


  3%|██▏                                                                               | 6/225 [00:03<01:59,  1.83it/s]

500  th batch loss :  tensor(0.2562, grad_fn=<MseLossBackward>)


  3%|██▌                                                                               | 7/225 [00:03<01:57,  1.85it/s]

600  th batch loss :  tensor(0.2492, grad_fn=<MseLossBackward>)


  4%|██▉                                                                               | 8/225 [00:04<01:52,  1.92it/s]

700  th batch loss :  tensor(0.2469, grad_fn=<MseLossBackward>)


  4%|███▎                                                                              | 9/225 [00:04<01:49,  1.98it/s]

800  th batch loss :  tensor(0.2560, grad_fn=<MseLossBackward>)


  4%|███▌                                                                             | 10/225 [00:05<01:44,  2.06it/s]

900  th batch loss :  tensor(0.2506, grad_fn=<MseLossBackward>)


  5%|███▉                                                                             | 11/225 [00:05<01:43,  2.07it/s]

1000  th batch loss :  tensor(0.2449, grad_fn=<MseLossBackward>)


  5%|████▎                                                                            | 12/225 [00:06<01:41,  2.10it/s]

1100  th batch loss :  tensor(0.2499, grad_fn=<MseLossBackward>)


  6%|████▋                                                                            | 13/225 [00:06<01:49,  1.94it/s]

1200  th batch loss :  tensor(0.2491, grad_fn=<MseLossBackward>)


  6%|█████                                                                            | 14/225 [00:07<01:47,  1.97it/s]

1300  th batch loss :  tensor(0.2559, grad_fn=<MseLossBackward>)


  7%|█████▍                                                                           | 15/225 [00:07<01:43,  2.04it/s]

1400  th batch loss :  tensor(0.2549, grad_fn=<MseLossBackward>)


  7%|█████▊                                                                           | 16/225 [00:08<01:42,  2.04it/s]

1500  th batch loss :  tensor(0.2467, grad_fn=<MseLossBackward>)


  8%|██████                                                                           | 17/225 [00:08<01:39,  2.09it/s]

1600  th batch loss :  tensor(0.2475, grad_fn=<MseLossBackward>)


  8%|██████▍                                                                          | 18/225 [00:09<01:35,  2.17it/s]

1700  th batch loss :  tensor(0.2554, grad_fn=<MseLossBackward>)


  8%|██████▊                                                                          | 19/225 [00:09<01:35,  2.16it/s]

1800  th batch loss :  tensor(0.2534, grad_fn=<MseLossBackward>)


  9%|███████▏                                                                         | 20/225 [00:10<01:36,  2.13it/s]

1900  th batch loss :  tensor(0.2495, grad_fn=<MseLossBackward>)


  9%|███████▌                                                                         | 21/225 [00:10<01:38,  2.07it/s]

2000  th batch loss :  tensor(0.2488, grad_fn=<MseLossBackward>)


 10%|███████▉                                                                         | 22/225 [00:10<01:36,  2.10it/s]

2100  th batch loss :  tensor(0.2498, grad_fn=<MseLossBackward>)


 10%|████████▎                                                                        | 23/225 [00:11<01:39,  2.03it/s]

2200  th batch loss :  tensor(0.2530, grad_fn=<MseLossBackward>)


 11%|████████▋                                                                        | 24/225 [00:12<01:39,  2.03it/s]

2300  th batch loss :  tensor(0.2499, grad_fn=<MseLossBackward>)


 11%|█████████                                                                        | 25/225 [00:12<01:37,  2.06it/s]

2400  th batch loss :  tensor(0.2493, grad_fn=<MseLossBackward>)


 12%|█████████▎                                                                       | 26/225 [00:12<01:33,  2.12it/s]

2500  th batch loss :  tensor(0.2505, grad_fn=<MseLossBackward>)


 12%|█████████▋                                                                       | 27/225 [00:13<01:36,  2.05it/s]

2600  th batch loss :  tensor(0.2500, grad_fn=<MseLossBackward>)


 12%|██████████                                                                       | 28/225 [00:13<01:34,  2.09it/s]

2700  th batch loss :  tensor(0.2500, grad_fn=<MseLossBackward>)


 13%|██████████▍                                                                      | 29/225 [00:14<01:33,  2.09it/s]

2800  th batch loss :  tensor(0.2509, grad_fn=<MseLossBackward>)


 13%|██████████▊                                                                      | 30/225 [00:14<01:36,  2.02it/s]

2900  th batch loss :  tensor(0.2500, grad_fn=<MseLossBackward>)


 14%|███████████▏                                                                     | 31/225 [00:15<01:36,  2.01it/s]

3000  th batch loss :  tensor(0.2492, grad_fn=<MseLossBackward>)


 14%|███████████▌                                                                     | 32/225 [00:15<01:35,  2.02it/s]

3100  th batch loss :  tensor(0.2490, grad_fn=<MseLossBackward>)


 15%|███████████▉                                                                     | 33/225 [00:16<01:34,  2.02it/s]

3200  th batch loss :  tensor(0.2519, grad_fn=<MseLossBackward>)


 15%|████████████▏                                                                    | 34/225 [00:16<01:35,  2.01it/s]

3300  th batch loss :  tensor(0.2513, grad_fn=<MseLossBackward>)


 16%|████████████▌                                                                    | 35/225 [00:17<01:34,  2.01it/s]

3400  th batch loss :  tensor(0.2504, grad_fn=<MseLossBackward>)


 16%|████████████▉                                                                    | 36/225 [00:17<01:34,  2.00it/s]

3500  th batch loss :  tensor(0.2505, grad_fn=<MseLossBackward>)


 16%|█████████████▎                                                                   | 37/225 [00:18<01:41,  1.85it/s]

3600  th batch loss :  tensor(0.2498, grad_fn=<MseLossBackward>)


 17%|█████████████▋                                                                   | 38/225 [00:19<01:44,  1.79it/s]

3700  th batch loss :  tensor(0.2494, grad_fn=<MseLossBackward>)


 17%|██████████████                                                                   | 39/225 [00:19<01:43,  1.80it/s]

3800  th batch loss :  tensor(0.2490, grad_fn=<MseLossBackward>)


 18%|██████████████▍                                                                  | 40/225 [00:20<01:41,  1.82it/s]

3900  th batch loss :  tensor(0.2485, grad_fn=<MseLossBackward>)


 18%|██████████████▊                                                                  | 41/225 [00:20<01:38,  1.86it/s]

4000  th batch loss :  tensor(0.2519, grad_fn=<MseLossBackward>)


 19%|███████████████                                                                  | 42/225 [00:21<01:39,  1.84it/s]

4100  th batch loss :  tensor(0.2514, grad_fn=<MseLossBackward>)


 19%|███████████████▍                                                                 | 43/225 [00:22<01:51,  1.64it/s]

4200  th batch loss :  tensor(0.2503, grad_fn=<MseLossBackward>)


 20%|███████████████▊                                                                 | 44/225 [00:22<01:48,  1.67it/s]

4300  th batch loss :  tensor(0.2493, grad_fn=<MseLossBackward>)


 20%|████████████████▏                                                                | 45/225 [00:23<01:59,  1.50it/s]

4400  th batch loss :  tensor(0.2518, grad_fn=<MseLossBackward>)


 20%|████████████████▌                                                                | 46/225 [00:24<01:58,  1.51it/s]

4500  th batch loss :  tensor(0.2510, grad_fn=<MseLossBackward>)


 21%|████████████████▉                                                                | 47/225 [00:24<01:48,  1.64it/s]

4600  th batch loss :  tensor(0.2492, grad_fn=<MseLossBackward>)


 21%|█████████████████▎                                                               | 48/225 [00:25<01:41,  1.75it/s]

4700  th batch loss :  tensor(0.2483, grad_fn=<MseLossBackward>)


 22%|█████████████████▋                                                               | 49/225 [00:25<01:35,  1.84it/s]

4800  th batch loss :  tensor(0.2491, grad_fn=<MseLossBackward>)


 22%|██████████████████                                                               | 50/225 [00:25<01:29,  1.95it/s]

4900  th batch loss :  tensor(0.2486, grad_fn=<MseLossBackward>)


 23%|██████████████████▎                                                              | 51/225 [00:26<01:27,  2.00it/s]

5000  th batch loss :  tensor(0.2485, grad_fn=<MseLossBackward>)


 23%|██████████████████▋                                                              | 52/225 [00:26<01:26,  1.99it/s]

5100  th batch loss :  tensor(0.2516, grad_fn=<MseLossBackward>)


 24%|███████████████████                                                              | 53/225 [00:27<01:24,  2.03it/s]

5200  th batch loss :  tensor(0.2500, grad_fn=<MseLossBackward>)


 24%|███████████████████▍                                                             | 54/225 [00:27<01:23,  2.04it/s]

5300  th batch loss :  tensor(0.2467, grad_fn=<MseLossBackward>)


 24%|███████████████████▊                                                             | 55/225 [00:28<01:21,  2.08it/s]

5400  th batch loss :  tensor(0.2496, grad_fn=<MseLossBackward>)


 25%|████████████████████▏                                                            | 56/225 [00:28<01:18,  2.15it/s]

5500  th batch loss :  tensor(0.2506, grad_fn=<MseLossBackward>)


 25%|████████████████████▌                                                            | 57/225 [00:29<01:16,  2.19it/s]

5600  th batch loss :  tensor(0.2487, grad_fn=<MseLossBackward>)


 26%|████████████████████▉                                                            | 58/225 [00:29<01:16,  2.18it/s]

5700  th batch loss :  tensor(0.2477, grad_fn=<MseLossBackward>)


 26%|█████████████████████▏                                                           | 59/225 [00:30<01:21,  2.04it/s]

5800  th batch loss :  tensor(0.2466, grad_fn=<MseLossBackward>)


 27%|█████████████████████▌                                                           | 60/225 [00:30<01:18,  2.11it/s]

5900  th batch loss :  tensor(0.2472, grad_fn=<MseLossBackward>)


 27%|█████████████████████▉                                                           | 61/225 [00:31<01:16,  2.15it/s]

6000  th batch loss :  tensor(0.2472, grad_fn=<MseLossBackward>)


 28%|██████████████████████▎                                                          | 62/225 [00:31<01:16,  2.14it/s]

6100  th batch loss :  tensor(0.2484, grad_fn=<MseLossBackward>)


 28%|██████████████████████▋                                                          | 63/225 [00:32<01:14,  2.16it/s]

6200  th batch loss :  tensor(0.2467, grad_fn=<MseLossBackward>)


 28%|███████████████████████                                                          | 64/225 [00:32<01:14,  2.15it/s]

6300  th batch loss :  tensor(0.2441, grad_fn=<MseLossBackward>)


 29%|███████████████████████▍                                                         | 65/225 [00:32<01:12,  2.19it/s]

6400  th batch loss :  tensor(0.2472, grad_fn=<MseLossBackward>)


 29%|███████████████████████▊                                                         | 66/225 [00:33<01:12,  2.20it/s]

6500  th batch loss :  tensor(0.2382, grad_fn=<MseLossBackward>)


 30%|████████████████████████                                                         | 67/225 [00:33<01:11,  2.20it/s]

6600  th batch loss :  tensor(0.2547, grad_fn=<MseLossBackward>)


 30%|████████████████████████▍                                                        | 68/225 [00:34<01:21,  1.93it/s]

6700  th batch loss :  tensor(0.2452, grad_fn=<MseLossBackward>)


 31%|████████████████████████▊                                                        | 69/225 [00:35<01:17,  2.01it/s]

6800  th batch loss :  tensor(0.2462, grad_fn=<MseLossBackward>)


 31%|█████████████████████████▏                                                       | 70/225 [00:35<01:20,  1.93it/s]

6900  th batch loss :  tensor(0.2458, grad_fn=<MseLossBackward>)


 32%|█████████████████████████▌                                                       | 71/225 [00:36<01:18,  1.96it/s]

7000  th batch loss :  tensor(0.2349, grad_fn=<MseLossBackward>)


 32%|█████████████████████████▉                                                       | 72/225 [00:36<01:17,  1.97it/s]

7100  th batch loss :  tensor(0.2398, grad_fn=<MseLossBackward>)


 32%|██████████████████████████▎                                                      | 73/225 [00:37<01:17,  1.96it/s]

7200  th batch loss :  tensor(0.2460, grad_fn=<MseLossBackward>)


 33%|██████████████████████████▋                                                      | 74/225 [00:37<01:15,  1.99it/s]

7300  th batch loss :  tensor(0.2462, grad_fn=<MseLossBackward>)


 33%|███████████████████████████                                                      | 75/225 [00:38<01:15,  1.98it/s]

7400  th batch loss :  tensor(0.2489, grad_fn=<MseLossBackward>)


 34%|███████████████████████████▎                                                     | 76/225 [00:38<01:14,  2.01it/s]

7500  th batch loss :  tensor(0.2531, grad_fn=<MseLossBackward>)


 34%|███████████████████████████▋                                                     | 77/225 [00:39<01:11,  2.06it/s]

7600  th batch loss :  tensor(0.2392, grad_fn=<MseLossBackward>)


 35%|████████████████████████████                                                     | 78/225 [00:39<01:10,  2.08it/s]

7700  th batch loss :  tensor(0.2496, grad_fn=<MseLossBackward>)


 35%|████████████████████████████▍                                                    | 79/225 [00:39<01:08,  2.13it/s]

7800  th batch loss :  tensor(0.2433, grad_fn=<MseLossBackward>)


 36%|████████████████████████████▊                                                    | 80/225 [00:40<01:07,  2.14it/s]

7900  th batch loss :  tensor(0.2409, grad_fn=<MseLossBackward>)


 36%|█████████████████████████████▏                                                   | 81/225 [00:40<01:05,  2.20it/s]

8000  th batch loss :  tensor(0.2436, grad_fn=<MseLossBackward>)


 36%|█████████████████████████████▌                                                   | 82/225 [00:41<01:05,  2.20it/s]

8100  th batch loss :  tensor(0.2463, grad_fn=<MseLossBackward>)


 37%|█████████████████████████████▉                                                   | 83/225 [00:41<01:05,  2.17it/s]

8200  th batch loss :  tensor(0.2469, grad_fn=<MseLossBackward>)


 37%|██████████████████████████████▏                                                  | 84/225 [00:42<01:05,  2.16it/s]

8300  th batch loss :  tensor(0.2356, grad_fn=<MseLossBackward>)


 38%|██████████████████████████████▌                                                  | 85/225 [00:42<01:04,  2.18it/s]

8400  th batch loss :  tensor(0.2454, grad_fn=<MseLossBackward>)


 38%|██████████████████████████████▉                                                  | 86/225 [00:43<01:02,  2.21it/s]

8500  th batch loss :  tensor(0.2416, grad_fn=<MseLossBackward>)


 39%|███████████████████████████████▎                                                 | 87/225 [00:43<01:02,  2.23it/s]

8600  th batch loss :  tensor(0.2287, grad_fn=<MseLossBackward>)


 39%|███████████████████████████████▋                                                 | 88/225 [00:43<01:01,  2.24it/s]

8700  th batch loss :  tensor(0.2480, grad_fn=<MseLossBackward>)


 40%|████████████████████████████████                                                 | 89/225 [00:44<01:00,  2.23it/s]

8800  th batch loss :  tensor(0.2358, grad_fn=<MseLossBackward>)


 40%|████████████████████████████████▍                                                | 90/225 [00:44<00:59,  2.26it/s]

8900  th batch loss :  tensor(0.2336, grad_fn=<MseLossBackward>)


 40%|████████████████████████████████▊                                                | 91/225 [00:45<00:59,  2.27it/s]

9000  th batch loss :  tensor(0.2306, grad_fn=<MseLossBackward>)


 41%|█████████████████████████████████                                                | 92/225 [00:45<00:58,  2.26it/s]

9100  th batch loss :  tensor(0.2471, grad_fn=<MseLossBackward>)


 41%|█████████████████████████████████▍                                               | 93/225 [00:46<00:59,  2.23it/s]

9200  th batch loss :  tensor(0.2443, grad_fn=<MseLossBackward>)


 42%|█████████████████████████████████▊                                               | 94/225 [00:46<00:59,  2.20it/s]

9300  th batch loss :  tensor(0.2640, grad_fn=<MseLossBackward>)


 42%|██████████████████████████████████▏                                              | 95/225 [00:47<00:57,  2.26it/s]

9400  th batch loss :  tensor(0.2346, grad_fn=<MseLossBackward>)


 43%|██████████████████████████████████▌                                              | 96/225 [00:47<00:56,  2.29it/s]

9500  th batch loss :  tensor(0.2383, grad_fn=<MseLossBackward>)


 43%|██████████████████████████████████▉                                              | 97/225 [00:47<00:55,  2.30it/s]

9600  th batch loss :  tensor(0.2355, grad_fn=<MseLossBackward>)


 44%|███████████████████████████████████▎                                             | 98/225 [00:48<00:56,  2.24it/s]

9700  th batch loss :  tensor(0.2471, grad_fn=<MseLossBackward>)


 44%|███████████████████████████████████▋                                             | 99/225 [00:48<00:59,  2.12it/s]

9800  th batch loss :  tensor(0.2501, grad_fn=<MseLossBackward>)


 44%|███████████████████████████████████▌                                            | 100/225 [00:49<00:58,  2.14it/s]

9900  th batch loss :  tensor(0.2374, grad_fn=<MseLossBackward>)


 45%|███████████████████████████████████▉                                            | 101/225 [00:49<00:57,  2.15it/s]

10000  th batch loss :  tensor(0.2430, grad_fn=<MseLossBackward>)


 45%|████████████████████████████████████▎                                           | 102/225 [00:50<00:57,  2.13it/s]

10100  th batch loss :  tensor(0.2406, grad_fn=<MseLossBackward>)


 46%|████████████████████████████████████▌                                           | 103/225 [00:50<00:57,  2.14it/s]

10200  th batch loss :  tensor(0.2323, grad_fn=<MseLossBackward>)


 46%|████████████████████████████████████▉                                           | 104/225 [00:51<00:55,  2.17it/s]

10300  th batch loss :  tensor(0.2366, grad_fn=<MseLossBackward>)


 47%|█████████████████████████████████████▎                                          | 105/225 [00:51<00:56,  2.13it/s]

10400  th batch loss :  tensor(0.2292, grad_fn=<MseLossBackward>)


 47%|█████████████████████████████████████▋                                          | 106/225 [00:52<00:55,  2.16it/s]

10500  th batch loss :  tensor(0.2327, grad_fn=<MseLossBackward>)


 48%|██████████████████████████████████████                                          | 107/225 [00:52<00:54,  2.16it/s]

10600  th batch loss :  tensor(0.2369, grad_fn=<MseLossBackward>)


 48%|██████████████████████████████████████▍                                         | 108/225 [00:53<00:54,  2.15it/s]

10700  th batch loss :  tensor(0.2214, grad_fn=<MseLossBackward>)


 48%|██████████████████████████████████████▊                                         | 109/225 [00:53<00:53,  2.18it/s]

10800  th batch loss :  tensor(0.2375, grad_fn=<MseLossBackward>)


 49%|███████████████████████████████████████                                         | 110/225 [00:54<00:53,  2.15it/s]

10900  th batch loss :  tensor(0.2807, grad_fn=<MseLossBackward>)


 49%|███████████████████████████████████████▍                                        | 111/225 [00:54<00:53,  2.14it/s]

11000  th batch loss :  tensor(0.2296, grad_fn=<MseLossBackward>)


 50%|███████████████████████████████████████▊                                        | 112/225 [00:54<00:51,  2.19it/s]

11100  th batch loss :  tensor(0.2554, grad_fn=<MseLossBackward>)


 50%|████████████████████████████████████████▏                                       | 113/225 [00:55<00:51,  2.18it/s]

11200  th batch loss :  tensor(0.2345, grad_fn=<MseLossBackward>)


 51%|████████████████████████████████████████▌                                       | 114/225 [00:55<00:51,  2.16it/s]

11300  th batch loss :  tensor(0.2211, grad_fn=<MseLossBackward>)


 51%|████████████████████████████████████████▉                                       | 115/225 [00:56<00:51,  2.15it/s]

11400  th batch loss :  tensor(0.2315, grad_fn=<MseLossBackward>)


 52%|█████████████████████████████████████████▏                                      | 116/225 [00:56<00:51,  2.12it/s]

11500  th batch loss :  tensor(0.2397, grad_fn=<MseLossBackward>)


 52%|█████████████████████████████████████████▌                                      | 117/225 [00:57<00:49,  2.19it/s]

11600  th batch loss :  tensor(0.2391, grad_fn=<MseLossBackward>)


 52%|█████████████████████████████████████████▉                                      | 118/225 [00:57<00:48,  2.20it/s]

11700  th batch loss :  tensor(0.2378, grad_fn=<MseLossBackward>)


 53%|██████████████████████████████████████████▎                                     | 119/225 [00:58<00:47,  2.23it/s]

11800  th batch loss :  tensor(0.2526, grad_fn=<MseLossBackward>)


 53%|██████████████████████████████████████████▋                                     | 120/225 [00:58<00:47,  2.23it/s]

11900  th batch loss :  tensor(0.2291, grad_fn=<MseLossBackward>)


 54%|███████████████████████████████████████████                                     | 121/225 [00:59<00:45,  2.29it/s]

12000  th batch loss :  tensor(0.2310, grad_fn=<MseLossBackward>)


 54%|███████████████████████████████████████████▍                                    | 122/225 [00:59<00:45,  2.27it/s]

12100  th batch loss :  tensor(0.2272, grad_fn=<MseLossBackward>)


 55%|███████████████████████████████████████████▋                                    | 123/225 [00:59<00:45,  2.25it/s]

12200  th batch loss :  tensor(0.2170, grad_fn=<MseLossBackward>)


 55%|████████████████████████████████████████████                                    | 124/225 [01:00<00:44,  2.28it/s]

12300  th batch loss :  tensor(0.2471, grad_fn=<MseLossBackward>)


 56%|████████████████████████████████████████████▍                                   | 125/225 [01:00<00:44,  2.25it/s]

12400  th batch loss :  tensor(0.2286, grad_fn=<MseLossBackward>)


 56%|████████████████████████████████████████████▊                                   | 126/225 [01:01<00:43,  2.26it/s]

12500  th batch loss :  tensor(0.2389, grad_fn=<MseLossBackward>)


 56%|█████████████████████████████████████████████▏                                  | 127/225 [01:01<00:44,  2.20it/s]

12600  th batch loss :  tensor(0.2450, grad_fn=<MseLossBackward>)


 57%|█████████████████████████████████████████████▌                                  | 128/225 [01:02<00:44,  2.20it/s]

12700  th batch loss :  tensor(0.2326, grad_fn=<MseLossBackward>)


 57%|█████████████████████████████████████████████▊                                  | 129/225 [01:02<00:44,  2.16it/s]

12800  th batch loss :  tensor(0.2414, grad_fn=<MseLossBackward>)


 58%|██████████████████████████████████████████████▏                                 | 130/225 [01:03<00:43,  2.19it/s]

12900  th batch loss :  tensor(0.2475, grad_fn=<MseLossBackward>)


 58%|██████████████████████████████████████████████▌                                 | 131/225 [01:03<00:42,  2.21it/s]

13000  th batch loss :  tensor(0.2281, grad_fn=<MseLossBackward>)


 59%|██████████████████████████████████████████████▉                                 | 132/225 [01:04<00:42,  2.18it/s]

13100  th batch loss :  tensor(0.2361, grad_fn=<MseLossBackward>)


 59%|███████████████████████████████████████████████▎                                | 133/225 [01:04<00:41,  2.20it/s]

13200  th batch loss :  tensor(0.2222, grad_fn=<MseLossBackward>)


 60%|███████████████████████████████████████████████▋                                | 134/225 [01:04<00:40,  2.24it/s]

13300  th batch loss :  tensor(0.2302, grad_fn=<MseLossBackward>)


 60%|████████████████████████████████████████████████                                | 135/225 [01:05<00:40,  2.20it/s]

13400  th batch loss :  tensor(0.2254, grad_fn=<MseLossBackward>)


 60%|████████████████████████████████████████████████▎                               | 136/225 [01:05<00:40,  2.22it/s]

13500  th batch loss :  tensor(0.2345, grad_fn=<MseLossBackward>)


 61%|████████████████████████████████████████████████▋                               | 137/225 [01:06<00:39,  2.25it/s]

13600  th batch loss :  tensor(0.2144, grad_fn=<MseLossBackward>)


 61%|█████████████████████████████████████████████████                               | 138/225 [01:06<00:40,  2.17it/s]

13700  th batch loss :  tensor(0.2592, grad_fn=<MseLossBackward>)


 62%|█████████████████████████████████████████████████▍                              | 139/225 [01:07<00:38,  2.23it/s]

13800  th batch loss :  tensor(0.2385, grad_fn=<MseLossBackward>)


 62%|█████████████████████████████████████████████████▊                              | 140/225 [01:07<00:37,  2.25it/s]

13900  th batch loss :  tensor(0.2328, grad_fn=<MseLossBackward>)


 63%|██████████████████████████████████████████████████▏                             | 141/225 [01:08<00:37,  2.22it/s]

14000  th batch loss :  tensor(0.2282, grad_fn=<MseLossBackward>)


 63%|██████████████████████████████████████████████████▍                             | 142/225 [01:08<00:41,  1.98it/s]

14100  th batch loss :  tensor(0.2428, grad_fn=<MseLossBackward>)


 64%|██████████████████████████████████████████████████▊                             | 143/225 [01:09<00:39,  2.06it/s]

14200  th batch loss :  tensor(0.2330, grad_fn=<MseLossBackward>)


 64%|███████████████████████████████████████████████████▏                            | 144/225 [01:09<00:40,  2.01it/s]

14300  th batch loss :  tensor(0.2478, grad_fn=<MseLossBackward>)


 64%|███████████████████████████████████████████████████▌                            | 145/225 [01:10<00:39,  2.02it/s]

14400  th batch loss :  tensor(0.2329, grad_fn=<MseLossBackward>)


 65%|███████████████████████████████████████████████████▉                            | 146/225 [01:10<00:38,  2.05it/s]

14500  th batch loss :  tensor(0.2315, grad_fn=<MseLossBackward>)


 65%|████████████████████████████████████████████████████▎                           | 147/225 [01:11<00:37,  2.09it/s]

14600  th batch loss :  tensor(0.2364, grad_fn=<MseLossBackward>)


 66%|████████████████████████████████████████████████████▌                           | 148/225 [01:11<00:36,  2.13it/s]

14700  th batch loss :  tensor(0.2278, grad_fn=<MseLossBackward>)


 66%|████████████████████████████████████████████████████▉                           | 149/225 [01:11<00:36,  2.11it/s]

14800  th batch loss :  tensor(0.2408, grad_fn=<MseLossBackward>)


 67%|█████████████████████████████████████████████████████▎                          | 150/225 [01:12<00:35,  2.14it/s]

14900  th batch loss :  tensor(0.2428, grad_fn=<MseLossBackward>)


 67%|█████████████████████████████████████████████████████▋                          | 151/225 [01:12<00:34,  2.16it/s]

15000  th batch loss :  tensor(0.2442, grad_fn=<MseLossBackward>)


 68%|██████████████████████████████████████████████████████                          | 152/225 [01:13<00:33,  2.18it/s]

15100  th batch loss :  tensor(0.2425, grad_fn=<MseLossBackward>)


 68%|██████████████████████████████████████████████████████▍                         | 153/225 [01:13<00:32,  2.19it/s]

15200  th batch loss :  tensor(0.2308, grad_fn=<MseLossBackward>)


 68%|██████████████████████████████████████████████████████▊                         | 154/225 [01:14<00:32,  2.19it/s]

15300  th batch loss :  tensor(0.2297, grad_fn=<MseLossBackward>)


 69%|███████████████████████████████████████████████████████                         | 155/225 [01:14<00:31,  2.22it/s]

15400  th batch loss :  tensor(0.2266, grad_fn=<MseLossBackward>)


 69%|███████████████████████████████████████████████████████▍                        | 156/225 [01:15<00:31,  2.21it/s]

15500  th batch loss :  tensor(0.2481, grad_fn=<MseLossBackward>)


 70%|███████████████████████████████████████████████████████▊                        | 157/225 [01:15<00:30,  2.22it/s]

15600  th batch loss :  tensor(0.2366, grad_fn=<MseLossBackward>)


 70%|████████████████████████████████████████████████████████▏                       | 158/225 [01:16<00:30,  2.23it/s]

15700  th batch loss :  tensor(0.2210, grad_fn=<MseLossBackward>)


 71%|████████████████████████████████████████████████████████▌                       | 159/225 [01:16<00:29,  2.22it/s]

15800  th batch loss :  tensor(0.2164, grad_fn=<MseLossBackward>)


 71%|████████████████████████████████████████████████████████▉                       | 160/225 [01:16<00:29,  2.18it/s]

15900  th batch loss :  tensor(0.2239, grad_fn=<MseLossBackward>)


 72%|█████████████████████████████████████████████████████████▏                      | 161/225 [01:17<00:29,  2.20it/s]

16000  th batch loss :  tensor(0.2189, grad_fn=<MseLossBackward>)


 72%|█████████████████████████████████████████████████████████▌                      | 162/225 [01:17<00:28,  2.20it/s]

16100  th batch loss :  tensor(0.2525, grad_fn=<MseLossBackward>)


 72%|█████████████████████████████████████████████████████████▉                      | 163/225 [01:18<00:28,  2.18it/s]

16200  th batch loss :  tensor(0.2272, grad_fn=<MseLossBackward>)


 73%|██████████████████████████████████████████████████████████▎                     | 164/225 [01:18<00:28,  2.17it/s]

16300  th batch loss :  tensor(0.2077, grad_fn=<MseLossBackward>)


 73%|██████████████████████████████████████████████████████████▋                     | 165/225 [01:19<00:28,  2.11it/s]

16400  th batch loss :  tensor(0.2345, grad_fn=<MseLossBackward>)


 74%|███████████████████████████████████████████████████████████                     | 166/225 [01:19<00:27,  2.13it/s]

16500  th batch loss :  tensor(0.2212, grad_fn=<MseLossBackward>)


 74%|███████████████████████████████████████████████████████████▍                    | 167/225 [01:20<00:27,  2.15it/s]

16600  th batch loss :  tensor(0.2399, grad_fn=<MseLossBackward>)


 75%|███████████████████████████████████████████████████████████▋                    | 168/225 [01:20<00:26,  2.13it/s]

16700  th batch loss :  tensor(0.2287, grad_fn=<MseLossBackward>)


 75%|████████████████████████████████████████████████████████████                    | 169/225 [01:21<00:27,  2.03it/s]

16800  th batch loss :  tensor(0.2222, grad_fn=<MseLossBackward>)


 76%|████████████████████████████████████████████████████████████▍                   | 170/225 [01:22<00:31,  1.73it/s]

16900  th batch loss :  tensor(0.2340, grad_fn=<MseLossBackward>)


 76%|████████████████████████████████████████████████████████████▊                   | 171/225 [01:22<00:29,  1.84it/s]

17000  th batch loss :  tensor(0.2343, grad_fn=<MseLossBackward>)


 76%|█████████████████████████████████████████████████████████████▏                  | 172/225 [01:23<00:29,  1.82it/s]

17100  th batch loss :  tensor(0.2278, grad_fn=<MseLossBackward>)


 77%|█████████████████████████████████████████████████████████████▌                  | 173/225 [01:23<00:27,  1.91it/s]

17200  th batch loss :  tensor(0.2273, grad_fn=<MseLossBackward>)


 77%|█████████████████████████████████████████████████████████████▊                  | 174/225 [01:24<00:26,  1.96it/s]

17300  th batch loss :  tensor(0.2275, grad_fn=<MseLossBackward>)


 78%|██████████████████████████████████████████████████████████████▏                 | 175/225 [01:24<00:24,  2.02it/s]

17400  th batch loss :  tensor(0.2308, grad_fn=<MseLossBackward>)


 78%|██████████████████████████████████████████████████████████████▌                 | 176/225 [01:24<00:23,  2.06it/s]

17500  th batch loss :  tensor(0.2294, grad_fn=<MseLossBackward>)


 79%|██████████████████████████████████████████████████████████████▉                 | 177/225 [01:25<00:22,  2.12it/s]

17600  th batch loss :  tensor(0.2122, grad_fn=<MseLossBackward>)


 79%|███████████████████████████████████████████████████████████████▎                | 178/225 [01:25<00:22,  2.09it/s]

17700  th batch loss :  tensor(0.2496, grad_fn=<MseLossBackward>)


 80%|███████████████████████████████████████████████████████████████▋                | 179/225 [01:26<00:21,  2.12it/s]

17800  th batch loss :  tensor(0.2409, grad_fn=<MseLossBackward>)


 80%|████████████████████████████████████████████████████████████████                | 180/225 [01:26<00:21,  2.05it/s]

17900  th batch loss :  tensor(0.2284, grad_fn=<MseLossBackward>)


 80%|████████████████████████████████████████████████████████████████▎               | 181/225 [01:27<00:20,  2.12it/s]

18000  th batch loss :  tensor(0.2129, grad_fn=<MseLossBackward>)


 81%|████████████████████████████████████████████████████████████████▋               | 182/225 [01:27<00:20,  2.11it/s]

18100  th batch loss :  tensor(0.2202, grad_fn=<MseLossBackward>)


 81%|█████████████████████████████████████████████████████████████████               | 183/225 [01:28<00:20,  2.05it/s]

18200  th batch loss :  tensor(0.2146, grad_fn=<MseLossBackward>)


 82%|█████████████████████████████████████████████████████████████████▍              | 184/225 [01:28<00:20,  1.97it/s]

18300  th batch loss :  tensor(0.2187, grad_fn=<MseLossBackward>)


 82%|█████████████████████████████████████████████████████████████████▊              | 185/225 [01:29<00:20,  1.99it/s]

18400  th batch loss :  tensor(0.2080, grad_fn=<MseLossBackward>)


 83%|██████████████████████████████████████████████████████████████████▏             | 186/225 [01:29<00:19,  1.96it/s]

18500  th batch loss :  tensor(0.2154, grad_fn=<MseLossBackward>)


 83%|██████████████████████████████████████████████████████████████████▍             | 187/225 [01:30<00:20,  1.87it/s]

18600  th batch loss :  tensor(0.2255, grad_fn=<MseLossBackward>)


 84%|██████████████████████████████████████████████████████████████████▊             | 188/225 [01:30<00:19,  1.91it/s]

18700  th batch loss :  tensor(0.2199, grad_fn=<MseLossBackward>)


 84%|███████████████████████████████████████████████████████████████████▏            | 189/225 [01:31<00:18,  1.95it/s]

18800  th batch loss :  tensor(0.2087, grad_fn=<MseLossBackward>)


 84%|███████████████████████████████████████████████████████████████████▌            | 190/225 [01:32<00:19,  1.78it/s]

18900  th batch loss :  tensor(0.2064, grad_fn=<MseLossBackward>)


 85%|███████████████████████████████████████████████████████████████████▉            | 191/225 [01:32<00:18,  1.84it/s]

19000  th batch loss :  tensor(0.2272, grad_fn=<MseLossBackward>)


 85%|████████████████████████████████████████████████████████████████████▎           | 192/225 [01:33<00:17,  1.89it/s]

19100  th batch loss :  tensor(0.2335, grad_fn=<MseLossBackward>)


 86%|████████████████████████████████████████████████████████████████████▌           | 193/225 [01:33<00:17,  1.86it/s]

19200  th batch loss :  tensor(0.1844, grad_fn=<MseLossBackward>)


 86%|████████████████████████████████████████████████████████████████████▉           | 194/225 [01:34<00:16,  1.92it/s]

19300  th batch loss :  tensor(0.2127, grad_fn=<MseLossBackward>)


 87%|█████████████████████████████████████████████████████████████████████▎          | 195/225 [01:34<00:15,  1.99it/s]

19400  th batch loss :  tensor(0.2198, grad_fn=<MseLossBackward>)


 87%|█████████████████████████████████████████████████████████████████████▋          | 196/225 [01:35<00:14,  2.04it/s]

19500  th batch loss :  tensor(0.2305, grad_fn=<MseLossBackward>)


 88%|██████████████████████████████████████████████████████████████████████          | 197/225 [01:35<00:13,  2.03it/s]

19600  th batch loss :  tensor(0.1853, grad_fn=<MseLossBackward>)


 88%|██████████████████████████████████████████████████████████████████████▍         | 198/225 [01:36<00:14,  1.92it/s]

19700  th batch loss :  tensor(0.2207, grad_fn=<MseLossBackward>)


 88%|██████████████████████████████████████████████████████████████████████▊         | 199/225 [01:36<00:14,  1.82it/s]

19800  th batch loss :  tensor(0.2469, grad_fn=<MseLossBackward>)


 89%|███████████████████████████████████████████████████████████████████████         | 200/225 [01:37<00:12,  1.92it/s]

19900  th batch loss :  tensor(0.1873, grad_fn=<MseLossBackward>)


 89%|███████████████████████████████████████████████████████████████████████▍        | 201/225 [01:37<00:11,  2.02it/s]

20000  th batch loss :  tensor(0.2115, grad_fn=<MseLossBackward>)


 90%|███████████████████████████████████████████████████████████████████████▊        | 202/225 [01:38<00:11,  1.92it/s]

20100  th batch loss :  tensor(0.2213, grad_fn=<MseLossBackward>)


 90%|████████████████████████████████████████████████████████████████████████▏       | 203/225 [01:38<00:11,  1.92it/s]

20200  th batch loss :  tensor(0.2187, grad_fn=<MseLossBackward>)


 91%|████████████████████████████████████████████████████████████████████████▌       | 204/225 [01:39<00:10,  1.92it/s]

20300  th batch loss :  tensor(0.2115, grad_fn=<MseLossBackward>)


 91%|████████████████████████████████████████████████████████████████████████▉       | 205/225 [01:39<00:10,  1.91it/s]

20400  th batch loss :  tensor(0.2235, grad_fn=<MseLossBackward>)


 92%|█████████████████████████████████████████████████████████████████████████▏      | 206/225 [01:40<00:09,  1.98it/s]

20500  th batch loss :  tensor(0.2147, grad_fn=<MseLossBackward>)


 92%|█████████████████████████████████████████████████████████████████████████▌      | 207/225 [01:40<00:09,  1.98it/s]

20600  th batch loss :  tensor(0.2220, grad_fn=<MseLossBackward>)


 92%|█████████████████████████████████████████████████████████████████████████▉      | 208/225 [01:41<00:08,  2.04it/s]

20700  th batch loss :  tensor(0.2332, grad_fn=<MseLossBackward>)


 93%|██████████████████████████████████████████████████████████████████████████▎     | 209/225 [01:41<00:07,  2.05it/s]

20800  th batch loss :  tensor(0.2143, grad_fn=<MseLossBackward>)


 93%|██████████████████████████████████████████████████████████████████████████▋     | 210/225 [01:42<00:07,  2.04it/s]

20900  th batch loss :  tensor(0.2131, grad_fn=<MseLossBackward>)


 94%|███████████████████████████████████████████████████████████████████████████     | 211/225 [01:42<00:06,  2.06it/s]

21000  th batch loss :  tensor(0.2195, grad_fn=<MseLossBackward>)


 94%|███████████████████████████████████████████████████████████████████████████▍    | 212/225 [01:43<00:06,  2.10it/s]

21100  th batch loss :  tensor(0.2221, grad_fn=<MseLossBackward>)


 95%|███████████████████████████████████████████████████████████████████████████▋    | 213/225 [01:43<00:05,  2.11it/s]

21200  th batch loss :  tensor(0.2450, grad_fn=<MseLossBackward>)


 95%|████████████████████████████████████████████████████████████████████████████    | 214/225 [01:44<00:05,  2.14it/s]

21300  th batch loss :  tensor(0.1957, grad_fn=<MseLossBackward>)


 96%|████████████████████████████████████████████████████████████████████████████▍   | 215/225 [01:44<00:04,  2.17it/s]

21400  th batch loss :  tensor(0.2252, grad_fn=<MseLossBackward>)


 96%|████████████████████████████████████████████████████████████████████████████▊   | 216/225 [01:44<00:04,  2.19it/s]

21500  th batch loss :  tensor(0.2282, grad_fn=<MseLossBackward>)


 96%|█████████████████████████████████████████████████████████████████████████████▏  | 217/225 [01:45<00:03,  2.19it/s]

21600  th batch loss :  tensor(0.2152, grad_fn=<MseLossBackward>)


 97%|█████████████████████████████████████████████████████████████████████████████▌  | 218/225 [01:45<00:03,  2.20it/s]

21700  th batch loss :  tensor(0.2294, grad_fn=<MseLossBackward>)


 97%|█████████████████████████████████████████████████████████████████████████████▊  | 219/225 [01:46<00:02,  2.18it/s]

21800  th batch loss :  tensor(0.2096, grad_fn=<MseLossBackward>)


 98%|██████████████████████████████████████████████████████████████████████████████▏ | 220/225 [01:46<00:02,  2.18it/s]

21900  th batch loss :  tensor(0.2142, grad_fn=<MseLossBackward>)


 98%|██████████████████████████████████████████████████████████████████████████████▌ | 221/225 [01:47<00:01,  2.13it/s]

22000  th batch loss :  tensor(0.2313, grad_fn=<MseLossBackward>)


 99%|██████████████████████████████████████████████████████████████████████████████▉ | 222/225 [01:47<00:01,  2.11it/s]

22100  th batch loss :  tensor(0.2271, grad_fn=<MseLossBackward>)


 99%|███████████████████████████████████████████████████████████████████████████████▎| 223/225 [01:48<00:00,  2.11it/s]

22200  th batch loss :  tensor(0.2231, grad_fn=<MseLossBackward>)


100%|███████████████████████████████████████████████████████████████████████████████▋| 224/225 [01:48<00:00,  2.02it/s]

22300  th batch loss :  tensor(0.2225, grad_fn=<MseLossBackward>)


100%|████████████████████████████████████████████████████████████████████████████████| 225/225 [01:48<00:00,  2.06it/s]

22400  th batch loss :  tensor(0.2438, grad_fn=<MseLossBackward>)


In [12]:
correct = 0
total = 0
with torch.no_grad():
    for i in range(len(test_x)):
        real_class = torch.argmax(test_y[i])
        prediction = net(test_x[i].view(-1, 1, 48, 48))
        print(prediction)
        predicted_class = torch.argmax(prediction)
        if predicted_class == real_class:
            correct += 1
        total += 1
print("accurcy : ", round(correct/total, 3))

tensor([[0.4215, 0.5785]])
tensor([[0.5181, 0.4819]])
tensor([[0.2832, 0.7168]])
tensor([[0.5287, 0.4713]])
tensor([[0.7200, 0.2800]])
tensor([[0.3577, 0.6423]])
tensor([[0.4767, 0.5233]])
tensor([[0.4131, 0.5869]])
tensor([[0.4190, 0.5810]])
tensor([[0.5396, 0.4604]])
tensor([[0.3961, 0.6039]])
tensor([[0.2035, 0.7965]])
tensor([[0.3015, 0.6985]])
tensor([[0.2632, 0.7368]])
tensor([[0.2628, 0.7372]])
tensor([[0.2436, 0.7564]])
tensor([[0.2641, 0.7359]])
tensor([[0.3977, 0.6023]])
tensor([[0.3753, 0.6247]])
tensor([[0.3225, 0.6775]])
tensor([[0.5242, 0.4758]])
tensor([[0.3733, 0.6267]])
tensor([[0.4740, 0.5260]])
tensor([[0.2677, 0.7323]])
tensor([[0.5018, 0.4982]])
tensor([[0.2807, 0.7193]])
tensor([[0.4403, 0.5597]])
tensor([[0.5876, 0.4124]])
tensor([[0.4519, 0.5481]])
tensor([[0.2986, 0.7014]])
tensor([[0.3067, 0.6933]])
tensor([[0.2913, 0.7087]])
tensor([[0.6429, 0.3571]])
tensor([[0.5266, 0.4734]])
tensor([[0.3811, 0.6189]])
tensor([[0.3075, 0.6925]])
tensor([[0.6548, 0.3452]])
t

tensor([[0.2594, 0.7406]])
tensor([[0.3945, 0.6055]])
tensor([[0.5418, 0.4582]])
tensor([[0.4000, 0.6000]])
tensor([[0.3505, 0.6495]])
tensor([[0.2783, 0.7217]])
tensor([[0.2571, 0.7429]])
tensor([[0.3915, 0.6085]])
tensor([[0.3878, 0.6122]])
tensor([[0.2718, 0.7282]])
tensor([[0.5330, 0.4670]])
tensor([[0.5618, 0.4382]])
tensor([[0.2321, 0.7679]])
tensor([[0.2863, 0.7137]])
tensor([[0.5965, 0.4035]])
tensor([[0.3175, 0.6825]])
tensor([[0.3733, 0.6267]])
tensor([[0.4549, 0.5451]])
tensor([[0.3369, 0.6631]])
tensor([[0.2568, 0.7432]])
tensor([[0.2052, 0.7948]])
tensor([[0.5669, 0.4331]])
tensor([[0.2767, 0.7233]])
tensor([[0.5076, 0.4924]])
tensor([[0.2608, 0.7392]])
tensor([[0.6404, 0.3596]])
tensor([[0.3702, 0.6298]])
tensor([[0.3196, 0.6804]])
tensor([[0.7567, 0.2433]])
tensor([[0.3350, 0.6650]])
tensor([[0.3107, 0.6893]])
tensor([[0.5336, 0.4664]])
tensor([[0.3898, 0.6102]])
tensor([[0.5054, 0.4946]])
tensor([[0.2185, 0.7815]])
tensor([[0.2811, 0.7189]])
tensor([[0.3945, 0.6055]])
t

tensor([[0.4884, 0.5116]])
tensor([[0.8013, 0.1987]])
tensor([[0.2363, 0.7637]])
tensor([[0.4046, 0.5954]])
tensor([[0.3521, 0.6479]])
tensor([[0.7006, 0.2994]])
tensor([[0.4670, 0.5330]])
tensor([[0.3722, 0.6278]])
tensor([[0.2596, 0.7404]])
tensor([[0.4499, 0.5501]])
tensor([[0.3493, 0.6507]])
tensor([[0.5687, 0.4313]])
tensor([[0.3068, 0.6932]])
tensor([[0.2544, 0.7456]])
tensor([[0.4507, 0.5493]])
tensor([[0.6093, 0.3907]])
tensor([[0.5710, 0.4290]])
tensor([[0.5124, 0.4876]])
tensor([[0.5197, 0.4803]])
tensor([[0.5774, 0.4226]])
tensor([[0.6751, 0.3249]])
tensor([[0.2648, 0.7352]])
tensor([[0.4236, 0.5764]])
tensor([[0.5510, 0.4490]])
tensor([[0.5391, 0.4609]])
tensor([[0.2614, 0.7386]])
tensor([[0.6700, 0.3300]])
tensor([[0.3707, 0.6293]])
tensor([[0.5872, 0.4128]])
tensor([[0.4258, 0.5742]])
tensor([[0.2667, 0.7333]])
tensor([[0.6927, 0.3073]])
tensor([[0.3910, 0.6090]])
tensor([[0.3276, 0.6724]])
tensor([[0.4624, 0.5376]])
tensor([[0.4106, 0.5894]])
tensor([[0.4558, 0.5442]])
t

tensor([[0.4085, 0.5915]])
tensor([[0.3026, 0.6974]])
tensor([[0.2608, 0.7392]])
tensor([[0.2651, 0.7349]])
tensor([[0.3646, 0.6354]])
tensor([[0.4114, 0.5886]])
tensor([[0.6435, 0.3565]])
tensor([[0.4293, 0.5707]])
tensor([[0.2396, 0.7604]])
tensor([[0.4025, 0.5975]])
tensor([[0.2819, 0.7181]])
tensor([[0.2981, 0.7019]])
tensor([[0.2047, 0.7953]])
tensor([[0.4446, 0.5554]])
tensor([[0.5993, 0.4007]])
tensor([[0.3437, 0.6563]])
tensor([[0.3956, 0.6044]])
tensor([[0.2329, 0.7671]])
tensor([[0.3895, 0.6105]])
tensor([[0.4853, 0.5147]])
tensor([[0.6773, 0.3227]])
tensor([[0.4963, 0.5037]])
tensor([[0.3066, 0.6934]])
tensor([[0.4568, 0.5432]])
tensor([[0.6490, 0.3510]])
tensor([[0.3027, 0.6973]])
tensor([[0.2468, 0.7532]])
tensor([[0.2921, 0.7079]])
tensor([[0.6550, 0.3450]])
tensor([[0.2810, 0.7190]])
tensor([[0.3535, 0.6465]])
tensor([[0.3578, 0.6422]])
tensor([[0.3566, 0.6434]])
tensor([[0.4346, 0.5654]])
tensor([[0.2619, 0.7381]])
tensor([[0.2598, 0.7402]])
tensor([[0.3700, 0.6300]])
t

tensor([[0.3250, 0.6750]])
tensor([[0.2740, 0.7260]])
tensor([[0.3937, 0.6063]])
tensor([[0.4543, 0.5457]])
tensor([[0.4539, 0.5461]])
tensor([[0.6244, 0.3756]])
tensor([[0.5343, 0.4657]])
tensor([[0.5320, 0.4680]])
tensor([[0.4982, 0.5018]])
tensor([[0.1922, 0.8078]])
tensor([[0.3785, 0.6215]])
tensor([[0.3101, 0.6899]])
tensor([[0.2541, 0.7459]])
tensor([[0.3779, 0.6221]])
tensor([[0.2350, 0.7650]])
tensor([[0.2968, 0.7032]])
tensor([[0.4118, 0.5882]])
tensor([[0.2016, 0.7984]])
tensor([[0.6680, 0.3320]])
tensor([[0.3429, 0.6571]])
tensor([[0.3171, 0.6829]])
tensor([[0.2457, 0.7543]])
tensor([[0.4965, 0.5035]])
tensor([[0.4496, 0.5504]])
tensor([[0.7075, 0.2925]])
tensor([[0.3112, 0.6888]])
tensor([[0.2950, 0.7050]])
tensor([[0.3549, 0.6451]])
tensor([[0.4243, 0.5757]])
tensor([[0.1852, 0.8148]])
tensor([[0.2185, 0.7815]])
tensor([[0.2496, 0.7504]])
tensor([[0.1827, 0.8173]])
tensor([[0.6646, 0.3354]])
tensor([[0.5685, 0.4315]])
tensor([[0.3297, 0.6703]])
tensor([[0.3855, 0.6145]])
t

tensor([[0.5763, 0.4237]])
tensor([[0.2674, 0.7326]])
tensor([[0.2262, 0.7738]])
tensor([[0.4911, 0.5089]])
tensor([[0.5361, 0.4639]])
tensor([[0.3630, 0.6370]])
tensor([[0.2357, 0.7643]])
tensor([[0.6276, 0.3724]])
tensor([[0.3438, 0.6562]])
tensor([[0.2347, 0.7653]])
tensor([[0.2994, 0.7006]])
tensor([[0.3876, 0.6124]])
tensor([[0.4356, 0.5644]])
tensor([[0.4220, 0.5780]])
tensor([[0.7578, 0.2422]])
tensor([[0.4568, 0.5432]])
tensor([[0.5884, 0.4116]])
tensor([[0.6636, 0.3364]])
tensor([[0.3604, 0.6396]])
tensor([[0.3104, 0.6896]])
tensor([[0.3468, 0.6532]])
tensor([[0.4778, 0.5222]])
tensor([[0.4764, 0.5236]])
tensor([[0.3787, 0.6213]])
tensor([[0.6165, 0.3835]])
tensor([[0.4572, 0.5428]])
tensor([[0.5493, 0.4507]])
tensor([[0.3748, 0.6252]])
tensor([[0.4546, 0.5454]])
tensor([[0.3260, 0.6740]])
tensor([[0.5753, 0.4247]])
tensor([[0.3895, 0.6105]])
tensor([[0.3991, 0.6009]])
tensor([[0.5477, 0.4523]])
tensor([[0.4522, 0.5478]])
tensor([[0.3895, 0.6105]])
tensor([[0.4124, 0.5876]])
t

tensor([[0.5396, 0.4604]])
tensor([[0.3966, 0.6034]])
tensor([[0.2686, 0.7314]])
tensor([[0.4769, 0.5231]])
tensor([[0.4214, 0.5786]])
tensor([[0.3226, 0.6774]])
tensor([[0.4107, 0.5893]])
tensor([[0.2639, 0.7361]])
tensor([[0.4267, 0.5733]])
tensor([[0.2467, 0.7533]])
tensor([[0.3752, 0.6248]])
tensor([[0.2875, 0.7125]])
tensor([[0.7233, 0.2767]])
tensor([[0.5614, 0.4386]])
tensor([[0.2668, 0.7332]])
tensor([[0.3960, 0.6040]])
tensor([[0.3228, 0.6772]])
tensor([[0.2786, 0.7214]])
tensor([[0.2546, 0.7454]])
tensor([[0.4372, 0.5628]])
tensor([[0.3893, 0.6107]])
tensor([[0.5344, 0.4656]])
tensor([[0.6520, 0.3480]])
tensor([[0.2883, 0.7117]])
tensor([[0.2216, 0.7784]])
tensor([[0.4550, 0.5450]])
tensor([[0.4211, 0.5789]])
tensor([[0.3182, 0.6818]])
tensor([[0.4124, 0.5876]])
tensor([[0.3021, 0.6979]])
tensor([[0.5313, 0.4687]])
tensor([[0.1810, 0.8190]])
tensor([[0.3314, 0.6686]])
tensor([[0.4294, 0.5706]])
tensor([[0.3852, 0.6148]])
tensor([[0.6606, 0.3394]])
tensor([[0.5421, 0.4579]])
t

tensor([[0.3980, 0.6020]])
tensor([[0.3215, 0.6785]])
tensor([[0.4871, 0.5129]])
tensor([[0.2997, 0.7003]])
tensor([[0.4291, 0.5709]])
tensor([[0.4736, 0.5264]])
tensor([[0.3864, 0.6136]])
tensor([[0.4647, 0.5353]])
tensor([[0.2217, 0.7783]])
tensor([[0.4550, 0.5450]])
tensor([[0.5519, 0.4481]])
tensor([[0.5137, 0.4863]])
tensor([[0.4515, 0.5485]])
tensor([[0.2930, 0.7070]])
tensor([[0.3715, 0.6285]])
tensor([[0.2252, 0.7748]])
tensor([[0.4171, 0.5829]])
tensor([[0.3044, 0.6956]])
tensor([[0.6493, 0.3507]])
tensor([[0.4049, 0.5951]])
tensor([[0.3599, 0.6401]])
tensor([[0.3463, 0.6537]])
tensor([[0.4268, 0.5732]])
tensor([[0.5335, 0.4665]])
tensor([[0.3480, 0.6520]])
tensor([[0.3316, 0.6684]])
tensor([[0.2346, 0.7654]])
tensor([[0.4181, 0.5819]])
tensor([[0.6945, 0.3055]])
tensor([[0.6135, 0.3865]])
tensor([[0.2724, 0.7276]])
tensor([[0.3635, 0.6365]])
tensor([[0.2831, 0.7169]])
tensor([[0.4037, 0.5963]])
tensor([[0.4763, 0.5237]])
tensor([[0.2968, 0.7032]])
tensor([[0.5208, 0.4792]])
t

tensor([[0.4966, 0.5034]])
tensor([[0.3908, 0.6092]])
tensor([[0.5978, 0.4022]])
tensor([[0.6547, 0.3453]])
tensor([[0.4371, 0.5629]])
tensor([[0.5026, 0.4974]])
tensor([[0.1881, 0.8119]])
tensor([[0.2109, 0.7891]])
tensor([[0.2823, 0.7177]])
tensor([[0.5587, 0.4413]])
tensor([[0.2858, 0.7142]])
tensor([[0.2953, 0.7047]])
tensor([[0.2631, 0.7369]])
tensor([[0.6266, 0.3734]])
tensor([[0.3746, 0.6254]])
tensor([[0.3043, 0.6957]])
tensor([[0.4169, 0.5831]])
tensor([[0.5662, 0.4338]])
tensor([[0.2985, 0.7015]])
accurcy :  0.648


In [14]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
print(device)

cpu
